name: Ashwin De Silva
tagline: Applied Scientist at Amazon
email: ldesilv2 at jhu dot edu
url: https://laknath1996.github.io
links:
  - {label: Google Scholar, url: "https://scholar.google.com/citations?user=xqhwEGIAAAAJ"}
  - {label: GitHub, url: "https://github.com/Laknath1996"}
  - {label: LinkedIn, url: "https://www.linkedin.com/in/ashwin-de-silva-6852b14b"}
